### ISSUE TITLE
Error when running run.flowsom with meta.k set to 2

### ISSUE THREAD

**Issue by jamesboot** [ImmuneDynamics/Spectre#166]
Hello,

Thanks for a great package and documentation. Ran into an interesting problem. We are playing around with our clustering. When I set meta.k to 2 in the run.flowsom() function I get the following error:

```
Preparing data
Starting FlowSOM
Building SOM

Mapping data to SOM

Building MST

Error in 1:nrow(m) : argument of length 0
```

I don't get this error if I set the value greater than 2. Is there a reason for this? Any work around?

Cheers!

**Comment by ghar1821** [comment]
Hi there,

I think this is because the consensus hierarchical clustering algorithm used by FlowSOM by default try to cluster the data into 2 - maxK clusters. By setting meta.k to 2, you are indirectly also setting maxK to 2, which causes the consensus hierarchical clustering algorithm to raise an error as it expects maxK to be greater than 2. 

I don't think there is any work around this unfortunately.

**Comment by tomashhurst** [comment]
@ghar1821 I might add a more specific error message to `run.flowsom` to flag this if meta.k is set to 2.
