### ISSUE TITLE
Modified Bodenmiller segmentation pipeline - error with new version of IMCtools?

### ISSUE THREAD

**Issue by veenstje** [ImmuneDynamics/Spectre#32]
Hi Tom, I've followed your instructions for the Modified Bodenmiller segmentation pipeline, which I greatly appreciate for being so detailed. However, I'm encountering the below error very early in the Jupyter notebook. I'm wondering if this is occurring because of the updated version of IMCtools that has been released by the Bodenmiller group in the past year? Have you had success using the pipeline with the most recent version of IMCtools or are you encountering a similar error?  Thanks!

![error - modified](https://user-images.githubusercontent.com/83611550/117994475-93789780-b30e-11eb-96d6-a4a92d43e9a4.JPG)

**Comment by tomashhurst** [comment]
Hi @veenstje , I tested it with the last IMC tools update that I saw, but it's possible I missed something. Let me try re-installing it fresh and see if I come across the same issue. 

Just checking -- did you launch Jupyter from IMC tools in Anaconda?

![image](https://user-images.githubusercontent.com/11766139/118066162-8d072000-b3e1-11eb-967f-4bb345331a3e.png)

**Comment by veenstje** [comment]
Hi Tom, I did use Anaconda Navigator with the IMCtools environment to open a Jupyter notebook as you have shown here. I'm in the process of downloading everything for an install on a separate computer to see if the error persists. I will keep you posted on the result.

Thanks

**Comment by veenstje** [comment]
I performed a brand new install on a separate computer and have the same error occur unfortunately. 

![imctoolserror](https://user-images.githubusercontent.com/83611550/118148008-27656480-b3de-11eb-9a4c-a36380dc5082.PNG)

**Comment by tomashhurst** [comment]
Hi @veenstje ,

We've got a major update coming out shortly where you can do all of the above steps using Spectre (in R), so that should get around the issues you are having. I'm hoping to have this update out later in the week, however, you can try it out using the instructions [here](https://wiki.centenary.org.au/display/SPECTRE/Protocol%3A+multi-cut+cell+segmentation+using+Ilastik) for now if you wish. You will need to re-install Spectre using the ['spatial' branch](https://wiki.centenary.org.au/x/CT-DCw) -- feel free to try it out and let me know if it works for you.

Tom

**Comment by veenstje** [comment]
Ok, I look forward to your update!

Jesse Veenstra MD, PhD, MS, FAAD
Staff Dermatologist
Department of Dermatology​
Henry Ford Health System
3031 West Grand Blvd, Suite 800
Detroit, MI 48202
Office: 313-916-2151
Fax: 313-916-5334
[cid:ddd16e3f-811c-48f7-a680-e48e0023d99f]
________________________________

**Comment by tomashhurst** [comment]
@veenstje , just to keep you posted -- we are trying to wrap up our final tests for the segmentation stages, and we are hoping to have the update ready in the next couple of days.

**Comment by veenstje** [comment]
Thanks for the update Tom

Jesse Veenstra MD, PhD, MS, FAAD
Staff Dermatologist
Department of Dermatology​
Henry Ford Health System
3031 West Grand Blvd, Suite 800
Detroit, MI 48202
Office: 313-916-2151
Fax: 313-425-4609
[cid:f4912b04-85dd-435f-a16b-163583cc404b]
________________________________

**Comment by tomashhurst** [comment]
Hi @veenstje , we've release v0.5.0 which has the updated cell segmentation and spatial analysis workflows. Check out the [getting started](https://immunedynamics.io/spectre/getting-started/) page to update Spectre, and then check out the [spatial analysis](https://immunedynamics.io/spectre/spatial/) page for the update instructions. Essentially you can simply use R to create the objects required to use in Ilastik, rather than having to use Anaconda/Python.

**Comment by tomashhurst** [comment]
@veenstje give it a shot and let us know if it all works out. If there's any problems, feel free to post another issue or shoot us and email. 

Tom
