### ISSUE TITLE
Why is always that the first cluster is not shown in umap? Missing values Warning

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ImmuneDynamics/Spectre#89]
Hi there, 

After I ran run.umap(), I checked cluster 1 did have cells. 

<img width="369" alt="Screen Shot 2021-08-28 at 6 17 00 PM" src="https://user-images.githubusercontent.com/62179082/131225683-cbb45c4d-f691-41b8-a268-2cc80a3cc255.png">

But, when I visualized it, there was a warning saying "Warning: Removed 1 rows containing missing values (geom_label)" and cluster 1 appeared to disappear in the plot. 

Would you mind explaining what might cause it? 

Thank you for your help!

```
make.colour.plot(cell.Nosub_10, "UMAP_X", "UMAP_Y", "FlowSOM_metacluster", col.type = 'factor', add.label = TRUE)
```

<img width="440" alt="Screen Shot 2021-08-28 at 6 18 41 PM" src="https://user-images.githubusercontent.com/62179082/131225733-b4725065-8618-4b19-b689-b6a6232871f2.png">

**Comment by ghar1821** [comment]
I think it's just that the label 1 is missing from the plot, not the metacluster. I said this because there are 10 dots in the plot (each denotes a metacluster centroid). The dot at the top (y=8, x=-1) does not have a label, and that is likely to be metacluster 1. Metacluster 1 only has a small number of cells, hence it may not look too obvious on the umap plot where it is, but I can see a small hunt of red dots around where metacluster 1 centroid is (the black dot with no label).

**Comment by tomashhurst** [comment]
Indeed! The label for the dot right at the top intersects with the border, and so it gets cut off -- but the actual data points are there!

![image](https://user-images.githubusercontent.com/11766139/131237995-9776c564-56cf-4218-a488-146a9252b517.png)

**Comment by tomashhurst** [comment]
I'm going to close this one for now, but please reach out again if you have any further issues!

Tom

**Comment by denvercal1234GitHub** [comment]
Thank you very much, Tom!
